### ISSUE TITLE
Extend update_toolchain_version to also update Fedora release

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/ci#219]
We should be able to extend the existing script somehow. We should probably start by making a subparser for the current command-line arguments.

**Comment by bgurney-rh** [comment]
So, in other words, this is to create a submodule to modify the `image:` lines in GitHub Actions config files:

In stratisd:
```
.github/workflows/main.yml-431-  shell-checks:
.github/workflows/main.yml-432-    runs-on: ubuntu-18.04
.github/workflows/main.yml-433-    container:
.github/workflows/main.yml:434:      image: fedora:33
.github/workflows/main.yml-435-    steps:
.github/workflows/main.yml-436-      - uses: actions/checkout@v2
.github/workflows/main.yml-437-      - name: Install dependencies
.github/workflows/main.yml-438-        run: >
```

And:
```
  next-fedora-python-checks:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # PYTHON CHECKS ON NEXT FEDORA PYTHON AND PYTHON TOOLS VERSION
          - dependencies: >
              pylint
              python3-requests
              python3-pygithub
              python3-semantic_version
            image: fedora:34
            task: make -f Makefile lint
            working-directory: ./code_maintenance
```

Some of these are annotated with comments (much like I did with the Rust versions).  Most aren't.

Can we be certain that the "current" (f33) and "next" (f34) versions are able to be advanced as indicated, without running into problems?
